// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: chLamLib/chLam.proto

package chLamProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChLamPeer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *ChLamPeer) Reset() {
	*x = ChLamPeer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chLamLib_chLam_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChLamPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChLamPeer) ProtoMessage() {}

func (x *ChLamPeer) ProtoReflect() protoreflect.Message {
	mi := &file_chLamLib_chLam_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChLamPeer.ProtoReflect.Descriptor instead.
func (*ChLamPeer) Descriptor() ([]byte, []int) {
	return file_chLamLib_chLam_proto_rawDescGZIP(), []int{0}
}

func (x *ChLamPeer) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

var File_chLamLib_chLam_proto protoreflect.FileDescriptor

var file_chLamLib_chLam_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x68, 0x4c, 0x61, 0x6d, 0x4c, 0x69, 0x62, 0x2f, 0x63, 0x68, 0x4c, 0x61, 0x6d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1f, 0x0a, 0x09, 0x43, 0x68, 0x4c, 0x61, 0x6d, 0x50,
	0x65, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x32, 0x40, 0x0a, 0x15, 0x43, 0x68, 0x61, 0x6e, 0x64,
	0x79, 0x4c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74,
	0x12, 0x27, 0x0a, 0x0d, 0x43, 0x68, 0x4c, 0x61, 0x6d, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x12, 0x0a, 0x2e, 0x43, 0x68, 0x4c, 0x61, 0x6d, 0x50, 0x65, 0x65, 0x72, 0x1a, 0x0a, 0x2e,
	0x43, 0x68, 0x4c, 0x61, 0x6d, 0x50, 0x65, 0x65, 0x72, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x63,
	0x68, 0x4c, 0x61, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_chLamLib_chLam_proto_rawDescOnce sync.Once
	file_chLamLib_chLam_proto_rawDescData = file_chLamLib_chLam_proto_rawDesc
)

func file_chLamLib_chLam_proto_rawDescGZIP() []byte {
	file_chLamLib_chLam_proto_rawDescOnce.Do(func() {
		file_chLamLib_chLam_proto_rawDescData = protoimpl.X.CompressGZIP(file_chLamLib_chLam_proto_rawDescData)
	})
	return file_chLamLib_chLam_proto_rawDescData
}

var file_chLamLib_chLam_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chLamLib_chLam_proto_goTypes = []interface{}{
	(*ChLamPeer)(nil), // 0: ChLamPeer
}
var file_chLamLib_chLam_proto_depIdxs = []int32{
	0, // 0: ChandyLamportSnapshot.ChLamSnapshot:input_type -> ChLamPeer
	0, // 1: ChandyLamportSnapshot.ChLamSnapshot:output_type -> ChLamPeer
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chLamLib_chLam_proto_init() }
func file_chLamLib_chLam_proto_init() {
	if File_chLamLib_chLam_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chLamLib_chLam_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChLamPeer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chLamLib_chLam_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chLamLib_chLam_proto_goTypes,
		DependencyIndexes: file_chLamLib_chLam_proto_depIdxs,
		MessageInfos:      file_chLamLib_chLam_proto_msgTypes,
	}.Build()
	File_chLamLib_chLam_proto = out.File
	file_chLamLib_chLam_proto_rawDesc = nil
	file_chLamLib_chLam_proto_goTypes = nil
	file_chLamLib_chLam_proto_depIdxs = nil
}
