// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: protobuf/pb.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ReaderCounter_CountWord_FullMethodName = "/ReaderCounter/CountWord"
)

// ReaderCounterClient is the client API for ReaderCounter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReaderCounterClient interface {
	CountWord(ctx context.Context, in *Line, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type readerCounterClient struct {
	cc grpc.ClientConnInterface
}

func NewReaderCounterClient(cc grpc.ClientConnInterface) ReaderCounterClient {
	return &readerCounterClient{cc}
}

func (c *readerCounterClient) CountWord(ctx context.Context, in *Line, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, ReaderCounter_CountWord_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReaderCounterServer is the server API for ReaderCounter service.
// All implementations must embed UnimplementedReaderCounterServer
// for forward compatibility
type ReaderCounterServer interface {
	CountWord(context.Context, *Line) (*EmptyResponse, error)
	mustEmbedUnimplementedReaderCounterServer()
}

// UnimplementedReaderCounterServer must be embedded to have forward compatible implementations.
type UnimplementedReaderCounterServer struct {
}

func (UnimplementedReaderCounterServer) CountWord(context.Context, *Line) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountWord not implemented")
}
func (UnimplementedReaderCounterServer) mustEmbedUnimplementedReaderCounterServer() {}

// UnsafeReaderCounterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReaderCounterServer will
// result in compilation errors.
type UnsafeReaderCounterServer interface {
	mustEmbedUnimplementedReaderCounterServer()
}

func RegisterReaderCounterServer(s grpc.ServiceRegistrar, srv ReaderCounterServer) {
	s.RegisterService(&ReaderCounter_ServiceDesc, srv)
}

func _ReaderCounter_CountWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Line)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderCounterServer).CountWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderCounter_CountWord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderCounterServer).CountWord(ctx, req.(*Line))
	}
	return interceptor(ctx, in, info, handler)
}

// ReaderCounter_ServiceDesc is the grpc.ServiceDesc for ReaderCounter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReaderCounter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ReaderCounter",
	HandlerType: (*ReaderCounterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CountWord",
			Handler:    _ReaderCounter_CountWord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/pb.proto",
}

const (
	CounterSaver_SaveCount_FullMethodName = "/CounterSaver/SaveCount"
)

// CounterSaverClient is the client API for CounterSaver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CounterSaverClient interface {
	SaveCount(ctx context.Context, in *LineCount, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type counterSaverClient struct {
	cc grpc.ClientConnInterface
}

func NewCounterSaverClient(cc grpc.ClientConnInterface) CounterSaverClient {
	return &counterSaverClient{cc}
}

func (c *counterSaverClient) SaveCount(ctx context.Context, in *LineCount, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, CounterSaver_SaveCount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CounterSaverServer is the server API for CounterSaver service.
// All implementations must embed UnimplementedCounterSaverServer
// for forward compatibility
type CounterSaverServer interface {
	SaveCount(context.Context, *LineCount) (*EmptyResponse, error)
	mustEmbedUnimplementedCounterSaverServer()
}

// UnimplementedCounterSaverServer must be embedded to have forward compatible implementations.
type UnimplementedCounterSaverServer struct {
}

func (UnimplementedCounterSaverServer) SaveCount(context.Context, *LineCount) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveCount not implemented")
}
func (UnimplementedCounterSaverServer) mustEmbedUnimplementedCounterSaverServer() {}

// UnsafeCounterSaverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CounterSaverServer will
// result in compilation errors.
type UnsafeCounterSaverServer interface {
	mustEmbedUnimplementedCounterSaverServer()
}

func RegisterCounterSaverServer(s grpc.ServiceRegistrar, srv CounterSaverServer) {
	s.RegisterService(&CounterSaver_ServiceDesc, srv)
}

func _CounterSaver_SaveCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LineCount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterSaverServer).SaveCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CounterSaver_SaveCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterSaverServer).SaveCount(ctx, req.(*LineCount))
	}
	return interceptor(ctx, in, info, handler)
}

// CounterSaver_ServiceDesc is the grpc.ServiceDesc for CounterSaver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CounterSaver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CounterSaver",
	HandlerType: (*CounterSaverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveCount",
			Handler:    _CounterSaver_SaveCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/pb.proto",
}

const (
	ServiceRegistry_RegisterPeer_FullMethodName = "/ServiceRegistry/RegisterPeer"
	ServiceRegistry_NewPeerAdded_FullMethodName = "/ServiceRegistry/NewPeerAdded"
)

// ServiceRegistryClient is the client API for ServiceRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceRegistryClient interface {
	RegisterPeer(ctx context.Context, in *Peer, opts ...grpc.CallOption) (*RegisterPeerResponse, error)
	NewPeerAdded(ctx context.Context, in *Peer, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type serviceRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceRegistryClient(cc grpc.ClientConnInterface) ServiceRegistryClient {
	return &serviceRegistryClient{cc}
}

func (c *serviceRegistryClient) RegisterPeer(ctx context.Context, in *Peer, opts ...grpc.CallOption) (*RegisterPeerResponse, error) {
	out := new(RegisterPeerResponse)
	err := c.cc.Invoke(ctx, ServiceRegistry_RegisterPeer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceRegistryClient) NewPeerAdded(ctx context.Context, in *Peer, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, ServiceRegistry_NewPeerAdded_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceRegistryServer is the server API for ServiceRegistry service.
// All implementations must embed UnimplementedServiceRegistryServer
// for forward compatibility
type ServiceRegistryServer interface {
	RegisterPeer(context.Context, *Peer) (*RegisterPeerResponse, error)
	NewPeerAdded(context.Context, *Peer) (*EmptyResponse, error)
	mustEmbedUnimplementedServiceRegistryServer()
}

// UnimplementedServiceRegistryServer must be embedded to have forward compatible implementations.
type UnimplementedServiceRegistryServer struct {
}

func (UnimplementedServiceRegistryServer) RegisterPeer(context.Context, *Peer) (*RegisterPeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterPeer not implemented")
}
func (UnimplementedServiceRegistryServer) NewPeerAdded(context.Context, *Peer) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewPeerAdded not implemented")
}
func (UnimplementedServiceRegistryServer) mustEmbedUnimplementedServiceRegistryServer() {}

// UnsafeServiceRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceRegistryServer will
// result in compilation errors.
type UnsafeServiceRegistryServer interface {
	mustEmbedUnimplementedServiceRegistryServer()
}

func RegisterServiceRegistryServer(s grpc.ServiceRegistrar, srv ServiceRegistryServer) {
	s.RegisterService(&ServiceRegistry_ServiceDesc, srv)
}

func _ServiceRegistry_RegisterPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Peer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServer).RegisterPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceRegistry_RegisterPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServer).RegisterPeer(ctx, req.(*Peer))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceRegistry_NewPeerAdded_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Peer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServer).NewPeerAdded(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceRegistry_NewPeerAdded_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServer).NewPeerAdded(ctx, req.(*Peer))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceRegistry_ServiceDesc is the grpc.ServiceDesc for ServiceRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ServiceRegistry",
	HandlerType: (*ServiceRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterPeer",
			Handler:    _ServiceRegistry_RegisterPeer_Handler,
		},
		{
			MethodName: "NewPeerAdded",
			Handler:    _ServiceRegistry_NewPeerAdded_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/pb.proto",
}
